version: "2"
services:
  pgweb:
    build:
      context: .
      dockerfile: Dockerfile.pgweb
    image: registry.devshift.net/bayesian/coreapi-pgweb:latest
    ports:
     - "31003:8080"
    depends_on:
     - pgbouncer
    environment:
      DATABASE_URL: "postgres://coreapi:coreapi@coreapi-pgbouncer:5432/coreapi?sslmode=disable"
    restart: always
    container_name: coreapi-pgweb
